apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-only
rules:
- apiGroups: ["*"]
  resources: [
    "pods", 
    "services", 
    "endpoints", 
    "persistentvolumeclaims", 
    "events", 
    "configmaps", 
    "namespaces", 
    "daemonsets", 
    "deployments", 
    "replicasets", 
    "statefulsets", 
    "cronjobs", 
    "jobs", 
    "horizontalpodautoscalers", 
    "ingresses", 
    "networkpolicies", 
    "clusterroles", 
    "clusterrolebindings", 
    "roles", 
    "rolebindings", 
    "storageclasses", 
    "volumeattachments"
  ]
  verbs: [
    "get", 
    "list", 
    "watch"
  ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:read-only
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read-only
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:read-only