apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  ttlSecondsAfterEmpty: 60 # scale down nodes after 60 seconds without workloads (excluding daemons)
  limits:
    resources:
      cpu: 1000
      memory: 1000Gi # limit to 100 CPU cores
  requirements:
    # Include general purpose instance families
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: [m5]
    # Exclude small instance sizes
    - key: karpenter.k8s.aws/instance-size
      operator: NotIn
      values: [nano, micro, small]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
  consolidation:
    enabled: true
  providerRef:
    name: provider